---
title: "Intraday/daily/weekly forecast"
author: "Ben Schiek"
date: "`r Sys.time()` (local time)"
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
output: 
  pdf_document:
    fig_caption: true
    number_sections: true
    latex_engine: xelatex
mainfont: Garamond
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(tidyquant)
library(WaveletComp)
library(patchwork)
library(kableExtra)
library(xtable)
library(flextable)
#========================================================================
# Define functions
#========================================================================
fitWave <- function(ts, per_vec, pval_thresh = 0.01, n_lookAhead){
  n_t <- length(ts)
  t <- 1:n_t
  regrsrs_sin <- paste0("sin(2 * pi / per_vec[", c(1:length(per_vec)), "] * t)", collapse = " + ")
  regrsrs_cos <- paste0("cos(2 * pi / per_vec[", c(1:length(per_vec)), "] * t)", collapse = " + ")
  regrsrs <- paste(regrsrs_sin, regrsrs_cos, sep = " + ")
  this_formula <- as.formula(paste("ts ~ -1 +", regrsrs)[1])
  linmod <- lm(this_formula)
  summod <- summary(linmod)
  #summod
  pvals <- as.numeric(summod$coefficients[, 4])
  ind_rm <- which(pvals > pval_thresh)
  round <- 0
  while(length(ind_rm) > 0){
    round <- round + 1
    print(paste("round ", round))
    if(round == 7){
      print("Too many rounds, aborting.")
      break
    }
    regrsrs_char <- strsplit(as.character(regrsrs), " \\+ ")[[1]]
    regrsrs_char <- regrsrs_char[-ind_rm]
    regrsrs <- paste(regrsrs_char, collapse = " + ")
    this_formula <- as.formula(paste("ts ~ -1 +", regrsrs)[1])
    linmod <- lm(this_formula)
    #---------------------
    summod <- summary(linmod)
    #print(summod)
    pvals <- as.numeric(summod$coefficients[, 4])
    ind_rm <- which(pvals > pval_thresh)
  }
  fitted_wave <- fitted(linmod)
  t <- (n_t + 1):(n_t + n_lookAhead)
  regrsrs_fut <- names(linmod$coefficients)
  #regrsrs_fut <- gsub("t", "t_fut", regrsrs_fut)
  list_fut <- list()
  for(i in 1:length(regrsrs_fut)){
    list_fut[[i]] <- eval(parse(text = regrsrs_fut[i]))
  }
  df_fut <- as.data.frame(do.call(cbind, list_fut))
  predict_wave <- predict(linmod, df_fut, interval = "prediction")  
  print(summod)
  
  list_out <- list(fitted_wave, predict_wave, summod)
  return(list_out)
}
#========================================================================
plot_validation <- function(yhat, ypredict, df_wave){
  #df_plot <- df_wave[, c("date", "date_chr", "p", "ema", "slope")]
  df_plot <- df_wave[, c("date", "date_chr", "p", "ema", "pctlOsc")]
  df_plot$yhat <- c(yhat, ypredict[, 1])
  ind_divide <- length(yhat)
  # df_plot$set <- NA
  # df_plot$set[ind_fit] <- "fit"
  # df_plot$set[ind_test] <- "test"
  df_plot$yhat_p <- df_plot$p + df_plot$yhat
  my_breaks <- df_plot$date_chr[seq.int(1, length(df_plot$date_chr), length.out = 30)]
  df_plot <- df_plot %>% gather(Type, Value, p:yhat_p)
  df_plot$Value <- as.numeric(df_plot$Value)
  #unique(df_plot$Type)
  df_plot_ts <- subset(df_plot, Type %in% c("p", "ema", "yhat_p"))
  #df_plot_ts_dtFit <- subset(df_plot, Type %in% c("slope", "yhat"))
  df_plot_ts_dtFit <- subset(df_plot, Type %in% c("pctlOsc", "yhat"))
  
  n_types_fit <- length(unique(df_plot_ts_dtFit$Type))
  n_types_ts <- length(unique(df_plot_ts$Type))
  distinct_colors <- randomcoloR::distinctColorPalette(k = n_types_fit + n_types_ts)
  colors_dtFit <- distinct_colors[1:n_types_fit]
  colors_ts <- distinct_colors[(n_types_fit + 1):(n_types_fit + n_types_ts)]
  
  df_plot_ts_dtFit$date_chr <- as.factor(df_plot_ts_dtFit$date_chr)
  #df_plot_dt <- subset(df_plot_ts_dtFit, Type == "slope")
  df_plot_dt <- subset(df_plot_ts_dtFit, Type == "pctlOsc")
  df_plot_dtFit <- subset(df_plot_ts_dtFit, Type == "yhat")
  
  gg <- ggplot()
  gg <- gg + geom_line(data = df_plot_dtFit, aes(x = date_chr, y = Value, color = Type, group = 1), lwd = 1.1)#, color = colors_dtFit[2], lwd = 1.1)
  gg <- gg + geom_line(data = df_plot_dt, aes(x = date_chr, y = Value, color = Type, group = 1))#, color = colors_dtFit[1])
  gg <- gg + scale_color_manual(values = colors_dtFit)
  gg <- gg + geom_hline(yintercept = 0, color = "violet", lwd = 1)
  gg <- gg + geom_vline(aes(xintercept = ind_divide), lwd = 1, color = "violet")
  gg <- gg + theme_bw()
  gg <- gg + scale_x_discrete(breaks = my_breaks)
  gg <- gg + theme(axis.title = element_blank(),
                   legend.title = element_blank(),
                   axis.text.x = element_text(angle = 60, hjust = 1))
  #gg <- gg + scale_color_brewer(palette = "Dark2")
  gg_dtFit <- gg
  
  # df_plot_ts$date_chr <- as.factor(df_plot_ts$date_chr)
  # df_plot_yhat_p <- subset(df_plot_ts, Type == "yhat_p")
  # df_plot_p_ema <- subset(df_plot_ts, Type != "yhat_p")
  # gg <- ggplot()
  # gg <- gg + geom_line(data = df_plot_p_ema, aes(x = date_chr, y = Value, group = Type, color = Type))
  # gg <- gg + scale_color_manual(values = colors_ts[1:2])
  # gg <- gg + geom_line(data = df_plot_yhat_p, aes(x = date_chr, y = Value, group = 1), color = colors_ts[3], lwd = 1.1)
  # gg <- gg + geom_vline(aes(xintercept = ind_divide), color = "violet", lwd = 1)
  # gg <- gg + theme_bw()
  # gg <- gg + scale_x_discrete(breaks = my_breaks)
  # gg <- gg + theme(axis.title = element_blank(),
  #                  axis.text.x = element_text(angle = 60, hjust = 1),
  #                  #legend.position = "bottom",
  #                  legend.title = element_blank())
  # gg_ts <- gg
  # 
  # gg_together <- gg_dtFit + gg_ts + plot_layout(ncol = 1, heights = c(2, 1))
  
  # print(gg_together)
  print(gg_dtFit)
}
#========================================================================
plot_prediction <- function(yhat, ypredict, df_wave, time_step, n_lookAhead = 34, n_lookAhead_zoom = 21, n_lookBack_zoom = 21){
  ind_end <- nrow(df_wave)
  #df_plot <- df_wave[, c("date", "date_chr", "slope")]
  df_plot <- df_wave[, c("date", "date_chr", "pctlOsc")]
  df_plot$yhat <- yhat
  df_plot$set <- "fit"
  df_plot$t <- NULL
  #---------------------------------------
  time_step_unit <- as.character(stringr::str_extract_all(time_step, "[a-z]+")[[1]])
  if(time_step_unit == "min"){
    time_step_num <- as.numeric(stringr::str_extract_all(time_step, "[0-9]+")[[1]])
    #time_step_num <- 60 * time_step_num
  }
  
  if(time_step_unit == "daily"){
    time_step_num <- 1
  }

  if(time_step_unit == "weekly"){
    time_step_num <- 1
  }
  # #---------------------------------------
  # future_start <- df_plot$date[nrow(df_plot)] + time_step_num
  # future_stop <- df_plot$date[nrow(df_plot)] + 2 * time_step_num * n_lookAhead
  # date_fut <- seq(future_start, future_stop, by = time_step_num)
  # date_fut <- date_fut[!weekdays(date_fut) %in% c('Saturday','Sunday')]
  # date_fut <- date_fut[1:n_lookAhead]
  # date_fut_chr <- as.character(date_fut)
  date_fut <- 1:n_lookAhead * time_step_num
  if(time_step_unit == "min"){
    date_fut <- round(date_fut / 60, 2)
    time_step_unit <- "hrs"
  }
  if(time_step_unit == "weekly"){
    # date_fut <- round(date_fut * 7, 2)
    # time_step_unit <- "days"
    time_step_unit <- "weeks"
  }
  if(time_step_unit == "daily"){
    time_step_unit <- "days"
  }
  
  date_fut_chr <- as.character(paste("+", date_fut, time_step_unit))
  #---------------------------------------
  #  df_add <- data.frame(date = date_fut, date_chr = date_fut_chr, slope = NA, yhat = ypredict[, 1], set = "predict")
  #df_add <- data.frame(date_chr = date_fut_chr, slope = NA, yhat = ypredict[, 1], set = "predict")
  df_add <- data.frame(date_chr = date_fut_chr, pctlOsc = NA, yhat = ypredict[, 1], set = "predict")
  df_plot$date <- NULL
  df_plot <- rbind(df_plot, df_add)
  df_plot$date_chr <- factor(df_plot$date_chr, levels = df_plot$date_chr)
  my_breaks <- df_plot$date_chr[seq.int(1, length(df_plot$date_chr), length.out = 30)]
  n <- 30
  distinct_colors <- randomcoloR::distinctColorPalette(k = n)
  colors_dtFit <- distinct_colors[sample(1:n, 2)]
  # df_plot_dt <- subset(df_plot, Type == "slope")
  # df_plot_dtFit <- subset(df_plot, Type == "yhat")
  this_title <- paste(c(paste(time_step, "chart"),
                        paste(per_ema_for_detrend, "step detrend")),
                      collapse = ", ")  
  gg <- ggplot()
  gg <- gg + geom_line(data = df_plot, aes(x = date_chr, y = yhat, group = 1), color = colors_dtFit[1], lwd = 1.1)
  # gg <- gg + geom_line(data = df_plot, aes(x = date_chr, y = slope, group = 1), color = colors_dtFit[2])
    gg <- gg + geom_line(data = df_plot, aes(x = date_chr, y = pctlOsc, group = 1), color = colors_dtFit[2])
  gg <- gg + geom_vline(xintercept = ind_end, color = "blue", size = 1)
  gg <- gg + scale_x_discrete(breaks = my_breaks)
  gg <- gg + geom_hline(yintercept = 0, color = "violet", size = 1)
  gg <- gg + labs(title = this_title)
  gg <- gg + theme_bw()
  gg <- gg + theme(axis.title = element_blank(),
                   axis.text.x = element_text(angle = 60, hjust = 1),
                   legend.title = element_blank(),
                   #legend.position = "top",
                   axis.ticks.x = element_blank(),
                   plot.title = element_text(size = 10))
  #gg <- gg + scale_color_brewer(palette = "Dark2")
  print(gg)
  
  
  # Zoom in
  ind_end_new <- n_lookBack_zoom
  df_plot_zoom <- df_plot[(ind_end - n_lookBack_zoom):(ind_end + n_lookAhead_zoom), ]
  my_breaks_zoom <- df_plot_zoom$date_chr[seq.int(1, length(df_plot_zoom$date_chr), length.out = 30)]
  gg <- ggplot()
  gg <- gg + geom_line(data = df_plot_zoom, aes(x = date_chr, y = yhat, group = 1), color = colors_dtFit[1], lwd = 1.1)
  # gg <- gg + geom_line(data = df_plot_zoom, aes(x = date_chr, y = slope, group = 1), color = colors_dtFit[2])
    gg <- gg + geom_line(data = df_plot_zoom, aes(x = date_chr, y = pctlOsc, group = 1), color = colors_dtFit[2])
  gg <- gg + geom_vline(xintercept = ind_end_new, color = "blue", size = 1)
  gg <- gg + scale_x_discrete(breaks = my_breaks_zoom)
  gg <- gg + geom_hline(yintercept = 0, color = "violet", size = 1)
  gg <- gg + labs(title = this_title)
  gg <- gg + theme_bw()
  gg <- gg + theme(axis.title = element_blank(),
                   axis.text.x = element_text(angle = 60, hjust = 1),
                   legend.title = element_blank(),
                   #legend.position = "top",
                   axis.ticks.x = element_blank(),
                   plot.title = element_text(size = 10))
  #gg <- gg + scale_color_brewer(palette = "Dark2")
  print(gg)
  
  
  
}
#========================================================================
get_cycles <- function(waveAnalysis){
  df_periodogram <- data.frame(period = waveAnalysis$Period, power = waveAnalysis$Power.avg)
  ind_critPoints <- findPeaks(df_periodogram$power)
  critPers <- df_periodogram$period[ind_critPoints]
  critPers
  #-------------------
  u <- df_periodogram$period
  if(max(u) > 1.5 * max(critPers)){
    ind_rm <- which(u > 1.5 * max(critPers))
    df_plot <- df_periodogram[-ind_rm, ]
  }else{
    df_plot <- df_periodogram
  }
  gg <- ggplot(df_plot, aes(x = period, y = power))
  gg <- gg + geom_line()
  gg <- gg + geom_vline(xintercept = critPers, color = "cyan", size = 1.2)
  gg <- gg + theme_bw()
  print(gg)
  #-------------------
  # Get periods, ordered from most power to least
  critPwrs <- df_periodogram$power[ind_critPoints]
  ind_order <- order(critPwrs, decreasing = T)
  per_vec <- critPers[ind_order]
  pwr_vec <- critPwrs[ind_order]
  df_mainCycles <- data.frame(Num = c(1:length(per_vec)), Period = per_vec, Power = pwr_vec)
  #-------------------
  return(df_mainCycles)
  
}
#========================================================================
# For percentile oscillator
pctileFun <- function(x){
  out <- ecdf(x)(x[length(x)])
  return(out)
}
#========================================================================
# Black-Scholes European call option value equation
OVfun <- function(X0, K, s, m, r, tau){
  d2 <- (log(X0 / K) + (m - s^2 / 2) * tau) / (s * sqrt(tau))
  N1 <- pnorm(d2 + s * sqrt(tau))
  N2 <- pnorm(d2)
  OV <- exp((m - r) * tau) * X0 * N1 - exp(-r * tau) * K * N2
  dfOut <- data.frame(OV, N1, N2)
  return(dfOut)
}
#========================================================================
# Financial "derivative" (i.e. derived from the Black-Scholes PDE)
# if \partial f / \partial t = 0
# The "intrinsic" option value apart from any time value
OVdt0 <- function(X0, K, s, m, r, tau){
  u <- 1 - 2 * m / s^2
  # Let g = moneyness (x(0) / K)
  gStar <- (1 / (1 - u))^(1 / u)
  Kstar <- gStar * X0
  OV <- exp(-r * tau) * K^(1 - u) / (2 * u) * (X0^u - K^u)
  dfOut <- data.frame(OV, mnyStar = gStar, Kstar)
  return(dfOut)
}
#========================================================================
# The derivative envelope, i.e. the derivative for which the action is stationary
OVstar <- function(X0, K, s, m, r, tau){
  d2 <- (log(X0 / K) + (m - s^2 / 2) * tau) / (s * sqrt(tau))
  OVstar <- K * (exp(-(m + s^2 / 2) * tau) / 2 - exp(-r * tau) * pnorm(d2))
  deltaStar <- K / (2 * X0) * exp(-(m + s^2 / 2) * tau)
  dfOut <- data.frame(OVstar, deltaStar)
  return(dfOut)
}
#========================================================================
#========================================================================
# End function definition
#========================================================================
#========================================================================

```


```{r, echo=FALSE}
#======================================================
# Set parameters
# If doing forex, then stock_symbol and crypto_symbol have to = NULL
#------------------------------------------------------
# Good setting for pctlOsc: weekly, rollWind=89
#chf/usd, cad/usd, weekly, rollWind=89
#usd/chf 15,5min maxlength=4000 rollWind=144,110
#SPY 1min maxlength4000 rollwind 233
#SPY 15min maxlength2000 rollwind 233
#SPY 30min maxlength3000 rollwind 300
#eur/jpy gbp/jpy usd/jpy 15min maxlength2000 rollwind 110/233
#eur/usd 5min rollwind233 perfect fit
#usd/cad maxlength3000 60min rollwind144 perfect
#eur/gbp maxlength3000 5min rollwind377
#GLD maxlength3-4000 5min rollwind233 GAZ too but less so
#aud/usd aud/jpy maxlength3000,4000 60or30min,5 rollwind144or233,110
#aud/jpy maxlength3000 5min rollwind233
#EWJ 4000 60min 233
#generally good: 4000, 5,60min 110
#------------------------------------------------------
symb_currency_from <- "gbp"#"chf"#"aud"#"gbp"#"eur"#"aud"#"gbp"#"aud"
symb_currency_to <- NULL#"jpy"
# OR stocks
stock_symbol <- "SPY"#"GAZ" #"GAZ" #"WTI"#NBO #"RTY=F"#"NK=F"#"NG=F"#"FXI"#"SI=F"#"GC=F"#"NG=F"#"CL=F"#"EXS1.DE"#ZC=F#"HG=F" BNO CPER XLF "XLI", "XLK", "IYR", "XLV", "XLY", "XLP"
#"ES=F", "GC=F", "NG=F", "CL=F", "CT=F", "KC=F", "CC=F", "SB=F", "ZB=F", "ZN=F", "ZF=F"
# OR crypto -- daily, weekly (from alpha advantage); or minute, hour from cryptocompare
crypto_symbol_from <- NULL#"ETH" #"BNB"#"BTC"
crypto_symbol_to <- "USD"#"ETH" #"BNB"#"BTC"
#------------------------------------------------------
time_step <- "30min" #1min, 5min, 15min, 30min, 60min, daily, weekly
#------------------------------------------------------
power_threshold <- "percentile log 0.1"#"drop lowest" #0.12
#------------------------------------------------------
max_length <- 4000 # max length of time series
rollWind <- 350
per_ema_for_detrend <- rollWind
backtest_fraction <- 1 / 8
lookAhead_fraction <- 1 / 8
lookBack_fraction <- lookAhead_fraction * 0.5
#waveletComp params:
lowerPeriod <- 2^2 #2 * slope, #2^1
upperPeriod <- 2^10 #floor(nrow(df_wave)/3)*slope, #2^7
#------------------------------------------------------
# Troubleshooting tips:
# -Just hit retry, sometimes it's an internet connection issue
# -Lower starting_how_many_steps_ago. (Has to be less than nrow of dataset.)
#------------------------------------------------------
if(!is.null(stock_symbol)){
  print(stock_symbol)
}else{
  if(is.null(symb_currency_from)){
    print(paste(crypto_symbol_from, "/", crypto_symbol_to))
  }else{
    print(paste(symb_currency_from, "/", symb_currency_to))
  }
}
print(time_step)
```

```{r, fig.show = 'hold', fig.align='center', fig.cap="\\label{fig:basic}(Top) Basic plot of time series with a moving average, and (bottom) the ts detrended.", fig.height=4, fig.width=7, echo=FALSE}
#======================================================
#fromdate <- Sys.Date() - starting_how_many_days_ago
# tbl_ohlcv <- tq_get(this_guy, get = "stock.prices", from = fromdate)
#tbl_ohlcv <- tq_get(currency_symbs, get = "stock.prices", from = fromdate)
# df_ohlcv <- as.data.frame(tbl_ohlcv)
time_step_unit <- as.character(stringr::str_extract_all(time_step, "[a-z]+")[[1]])
time_step_num <- as.numeric(stringr::str_extract_all(time_step, "[0-9]+")[[1]])

if(is.null(stock_symbol)){
  if(is.null(symb_currency_from)){
    symbol_domain <- "cryptocurrency"
    
  }else{
    symbol_domain <- "forex"
  }
}else{
  symbol_domain <- "stocks"
}

print(symbol_domain)

av_api_key("HQBAWJK4Y3YW81VG")
tiingo_api_key("36ed3f9ac9c2ba969b80c8389bc9a1e1fcdfcc42")
if(symbol_domain == "forex"){
  #--------------------------------------------------
  # If forex
  #--------------------------------------------------
  if(time_step_unit == "min"){
    # If intraday
     df_ohlcv <- tq_get(paste0(symb_currency_from, symb_currency_to),
       get        = "alphavantage",
       av_fun     = "TIME_SERIES_INTRADAY",
       interval   = time_step,
       outputsize = "full") %>% as.data.frame()
    # tbl_ohlcv <- tq_get("", get = "alphavantager", av_fun = "FX_INTRADAY", interval = time_step, from_symbol = symb_currency_from, to_symbol = symb_currency_to, outputsize = "full")
    #df_ohlcv <- as.data.frame(tbl_ohlcv)
    df_ohlcv$p <- rowSums(df_ohlcv[, c(3:5)]) / 3
  }
  if(time_step_unit == "daily"){
    # If daily
    df_ohlcv <- tq_get("", get = "alphavantager", av_fun = "FX_DAILY", from_symbol = symb_currency_from, to_symbol = symb_currency_to, outputsize = "full") %>% as.data.frame()
    df_ohlcv$p <- rowSums(df_ohlcv[, c(3:5)]) / 3
  }
  if(time_step_unit == "weekly"){
    # If weekly
    df_ohlcv <- tq_get("", get = "alphavantager", av_fun = "FX_WEEKLY", from_symbol = symb_currency_from, to_symbol = symb_currency_to, outputsize = "full") %>% as.data.frame()
    df_ohlcv$p <- rowSums(df_ohlcv[, c(3:5)]) / 3
  }
  df_ohlcv$symbol <- NULL
}
if(symbol_domain == "stocks"){
  #--------------------------------------------------
  # If stock
  #--------------------------------------------------
  if(time_step_unit == "min"){
    # If intraday
    # df_ohlcv <- stock_symbol %>%
    #   tq_get(get = "alphavantage", av_fun = "TIME_SERIES_INTRADAY", interval = time_step, outputsize = "full") %>% as.data.frame()
    # df_ohlcv$p <- rowSums(df_ohlcv[, c(3:5)]) / 3
    
    fromdate <- Sys.Date() - max_length / (7.5 * (60 / time_step_num))
    df_ohlcv <- stock_symbol %>% tq_get(get = "tiingo.iex",
       from   = fromdate,
       resample_frequency = time_step) %>% as.data.frame()
    df_ohlcv$p <- rowSums(df_ohlcv[, c(3:5)]) / 3


  }
  if(time_step_unit == "daily"){
    # If daily
    fromdate <- Sys.Date() - max_length
    df_ohlcv <- stock_symbol %>% tq_get(get = "stock.prices",
                                        from = fromdate) %>% as.data.frame()
    df_ohlcv$p <- df_ohlcv$adjusted
    # df_ohlcv <- stock_symbol %>%
    #   tq_get(get = "alphavantager", av_fun = "TIME_SERIES_DAILY_ADJUSTED", outputsize = "full") %>% as.data.frame(tbl_ohlcv)
    # df_ohlcv$p <- df_ohlcv$adjusted_close
  }
  if(time_step_unit == "weekly"){
    # If weekly
    fromdate <- Sys.Date() - max_length * 5
    df_ohlcv <- stock_symbol %>% tq_get(get = "stock.prices",
                                        from = fromdate,
                                        periodicity = time_step_unit) %>% as.data.frame()
    df_ohlcv$p <- df_ohlcv$adjusted

    # df_ohlcv <- stock_symbol %>%
    #   tq_get(get = "alphavantager", av_fun = "TIME_SERIES_WEEKLY_ADJUSTED", outputsize = "full") %>% as.data.frame()
    # df_ohlcv$p <- df_ohlcv$adjusted_close
  }
}

if(symbol_domain == "cryptocurrency"){
  #--------------------------------------------------
  # If cryptocurrency
  #--------------------------------------------------
  if(time_step_unit == "min"){
    # print("Intraday data not available for cryptocurrencies. Try daily or weekly.")
    fromdate <- Sys.Date() - max_length / (24 * (60 / time_step_num))
    df_ohlcv <- paste0(crypto_symbol_from, crypto_symbol_to) %>%
      tq_get(
       get    = "tiingo.crypto",
       from   = fromdate,
       resample_frequency = time_step) %>% as.data.frame()
    df_ohlcv$p <- (df_ohlcv$open + df_ohlcv$high + df_ohlcv$low) / 3
    
  }
  # If daily
  if(time_step_unit == "daily"){
    tbl_ohlcv <- crypto_symbol_from %>% tq_get(get = "alphavantager", av_fun = "DIGITAL_CURRENCY_DAILY", market = crypto_symbol_to)
    df_ohlcv <- as.data.frame(tbl_ohlcv)
    df_ohlcv$p <- rowSums(df_ohlcv[, 3:5]) / 3
  }
  if(time_step_unit == "weekly"){
    # If weekly
    #   fromdate <- Sys.Date() - max_length * 5
    #   df_ohlcv <- paste0(crypto_symbol_from, crypto_symbol_to) %>%
    #   tq_get(
    #    get    = "tiingo.crypto",
    #    from   = fromdate,
    #    resample_frequency = time_step) %>% as.data.frame()
    # df_ohlcv$p <- (df_ohlcv$open + df_ohlcv$high + df_ohlcv$low) / 3

    df_ohlcv <- crypto_symbol_from %>% tq_get(get = "alphavantager", av_fun = "DIGITAL_CURRENCY_WEEKLY", market = crypto_symbol_to, outputsize = "full") %>% as.data.frame()
    df_ohlcv$p <- rowSums(df_ohlcv[, 3:5]) / 3
  }
  
}
#--------------------------------------------------
u <- df_ohlcv$low
ind <- which(u == 0)
df_ohlcv$p[ind] <- mean(df_ohlcv$p[c((ind - 1), (ind + 1))])
#--------------------------------------------------
# Change time zone to New York, remove weekends
colnames(df_ohlcv)[which(colnames(df_ohlcv) == "timestamp")] <- "date"
this_tz <- "America/New_York"
attr(df_ohlcv$date, "tzone") <- this_tz
u <- df_ohlcv$date
if(symbol_domain == "forex"){
  # If forex, remove weekends (Friday 17:00-Sunday 17:00)
  #ind_Fri_16h <- which(weekdays(u) == "Friday" & hour(u) == 16)
  # if(length(ind_Fri_17h) != 0 & length(ind_Sun_17h) != 0){
  # ind_weekends_start <- ind_Fri_16h[c(1, (which(diff(ind_Fri_16h) != 1) + 1))]
  # ind_weekends_stop <- ind_Sun_17h[c(1, (which(diff(ind_Sun_17h) != 1) + 1))]
  ind_Fri_17h <- which(weekdays(u) == "Friday" & hour(u) == 17 & minute(u) == 0)
  ind_Sun_17h <- which(weekdays(u) == "Sunday" & hour(u) == 17 & minute(u) == 0)
  # if(length(ind_weekends_start) > length(ind_weekends_stop)){
  #   ind_weekends_stop <- c(ind_weekends_stop, length(u))
  
  if(length(ind_Fri_17h) != 0){
    if(ind_Fri_17h[1] > ind_Sun_17h[1]){
      ind_Fri_17h <- c(1, ind_Fri_17h)
    }
    
    if(length(ind_Fri_17h) > length(ind_Sun_17h)){
      ind_Sun_17h <- c(ind_Sun_17h, length(u))
      
    }
    #last_i <- length(ind_weekends_start)
    last_i <- length(ind_Fri_17h)
    list_ind_rm <- list()
    for(i in 1:last_i){
      # ind_rm <- ind_weekends_start[i]:ind_weekends_stop[i]
      ind_rm <- (ind_Fri_17h[i] + 1):ind_Sun_17h[i]
      list_ind_rm[[i]] <- ind_rm
    }
    ind_rm <- do.call(c, list_ind_rm)
    df_ohlcv <- df_ohlcv[-ind_rm, ]
  }
  
  u <- df_ohlcv$date
  ind_newYearsEve_17h <- which(day(u) == 31 & month(u) == 12 & hour(u) == 17 & minute(u) == 0)
  ind_newYearsDay_17h <- which(day(u) == 1 & month(u) == 1 & hour(u) == 17 & minute(u) == 0)
  ind_xmasEve_17h <- which(day(u) == 24 & month(u) == 12 & hour(u) == 17 & minute(u) == 0)
  ind_xmasDay_17h <- which(day(u) == 25 & month(u) == 12 & hour(u) == 17 & minute(u) == 0)

  if(length(ind_newYearsEve_17h) != 0 & length(ind_newYearsDay_17h) != 0){
    ind_rm <- ind_newYearsEve_17h:ind_newYearsDay_17h
    df_ohlcv <- df_ohlcv[-ind_rm, ]
  }
  
  if(length(ind_newYearsEve_17h) == 0 & length(ind_newYearsDay_17h) != 0){
    ind_rm <- 1:ind_newYearsDay_17h
    df_ohlcv <- df_ohlcv[-ind_rm, ]
  }

  if(length(ind_newYearsEve_17h) != 0 & length(ind_newYearsDay_17h) == 0){
    ind_rm <- ind_newYearsEve_17h:length(u)
    df_ohlcv <- df_ohlcv[-ind_rm, ]
  }
  
  
}
# if(symbol_domain == "stocks"){
#   if(stock_symbol == "ES=F"){
#     df_ohlcv <- df_ohlcv[!weekdays(u) %in% c('Saturday', 'Sunday'), ]
#     u <- df_ohlcv$date
#     df_ohlcv <- df_ohlcv[!hour(u) %in% c(16:24, 0:8), ]
#   }
#   
# }

print(paste("Charts are in", this_tz, "time."))
#--------------------------------------------------
# if(!is.null(starting_how_many_steps_ago)){
#   ind_now <- nrow(df_ohlcv)
#   if(starting_how_many_steps_ago > ind_now){
#     print("starting_how_many_steps_ago is greater than time series length.")
# print(paste("starting_how_many_steps_ago ="), starting_how_many_steps_ago)
# print(paste("steps in time series ="), ind_now)
# print("Reduce starting_how_many_steps_ago.")
#   }
#   df_ohlcv <- df_ohlcv[(ind_now - starting_how_many_steps_ago + 1):ind_now, ]
# }
ind_now <- nrow(df_ohlcv)
if(ind_now > max_length){
  df_ohlcv <- df_ohlcv[(ind_now - max_length + 1):ind_now, ]
}
#--------------------------------------------------

df <- df_ohlcv[, c("date", "p")]
df <- as.data.frame(df)
#df <- df %>% mutate(date = as.POSIXct(date, format = "%Y-%m-%d %H:%M:%S"))
o <- apply(df, 2, function(x) length(which(is.na(x))))
#table(o)
ind_na <- which(is.na(df$p))
if(length(ind_na) != 0){
  df$p <- na.approx(df$p)
}
#--------------------------------------------------------------
# Get p - EMA oscillator series
df$ema <- EMA(df$p, per_ema_for_detrend)
df$slope <- df$p - df$ema
#--------------------------------------------------------------
# Get p percentile oscillator series
df$pctlOsc <- rollapply(df$p, rollWind,
                        pctileFun, fill = NA,
                        align = "right")
df$pctlOsc <- df$pctlOsc - 1 / 2
# dfStk <- dfStk %>% group_by(symbol) %>%
#   mutate(pctlOsc = rollapply(p, rollWind, pctileFun, fill = NA, align = "right")) %>%
#   as.data.frame()
#--------------------------------------------------------------
# convert to character column and set up handy columns for making breaks
df <- df %>%
  mutate(date_chr = as.character(df$date),
         day = lubridate::day(date),
         hour = lubridate::hour(date),
         minute = lubridate::minute(date),
         new_day = if_else(day != lag(day) | is.na(lag(day)), 1, 0))
# breaks equally spaced
my_breaks <- df$date_chr[seq.int(1, length(df$date_chr), length.out = 30)]
#my_breaks <- df[df$minute == 0,]$date_chr
#my_breaks <- df[df$new_day == 1,]$date_chr
#------------------------------------------------------------
# Basic overview plot
gg <- ggplot(df, aes(x = date_chr, y = slope, group = 1))
gg <- gg + geom_line()
gg <- gg + scale_x_discrete(breaks = my_breaks)
gg <- gg + geom_hline(yintercept = 0, color = "violet")
gg <- gg + theme_bw()
gg <- gg + theme(axis.text.x = element_blank(),
                 axis.title.x = element_blank())
gg_dt <- gg

gg <- ggplot(df, aes(x = date_chr, y = pctlOsc, group = 1))
gg <- gg + geom_line()
gg <- gg + scale_x_discrete(breaks = my_breaks)
gg <- gg + geom_hline(yintercept = 0, color = "violet")
gg <- gg + theme_bw()
gg <- gg + theme(axis.text.x = element_text(angle = 60, hjust = 1),
                 axis.title.x = element_blank())
gg_pctlOsc <- gg
#------------------------------------------------------------
df_plot <- df[, c("date_chr", "p", "ema")]
colnames(df_plot)[3] <- paste("ema", per_ema_for_detrend)
# df_plot$ema_short <- EMA(df$p, per_ema_short)
# df_plot$ema_long <- EMA(df$p, per_ema_long)
# colnames(df_plot)[4] <- paste("ema", per_ema_short)
# colnames(df_plot)[5] <- paste("ema", per_ema_long)

gathercols <- colnames(df_plot)[2:ncol(df_plot)]
df_plot <- df_plot %>% gather_("Type", "p", gathercols)
sigP <- sd(df_plot$p, na.rm = T)
muP <- mean(df_plot$p, na.rm = T)
gg <- ggplot(df_plot, aes(x = date_chr, y = p, group = Type, color = Type))
gg <- gg + geom_line()
gg <- gg + geom_hline(yintercept = muP + 2 * sigP, color = "red")
gg <- gg + geom_hline(yintercept = muP - 2 * sigP, color = "red")
gg <- gg + geom_hline(yintercept = muP, color = "blue")
gg <- gg + scale_x_discrete(breaks = my_breaks)
gg <- gg + theme_bw()
gg <- gg + theme(legend.title = element_blank(),
                 axis.title.x = element_blank(),
                 axis.text.x = element_blank())
gg_raw <- gg
#------------------------------------------------------------
gg_raw / gg_dt / gg_pctlOsc / plot_layout(ncol = 1, heights = c(1, 1/2, 1/2, 1/4))
#------------------------------------------------------------

```

```{r, fig.show = 'hold', fig.align='center', fig.cap="\\label{fig:basic}(Top) Basic plot of time series with a moving average, and (bottom) the ts detrended.", fig.height=4, fig.width=7, echo=FALSE}

#-----------------------------------------------------------------------
# Calculate option value, intrinsic value, optimal strike, moneyness, etc.
#-----------------------------------------------------------------------
# Compute tSteps left until the end of the week
# Also get the appropriate discount rate for the tStep
# Continuous tStep discount rate is computed from an assumed discrete annual discount rate of 0.05
rYrly_discrete <- 0.05
timeNow <- Sys.time()
d0 <- 6 - wday(timeNow) # Days left in the trading week
h0 <- 24 - hour(timeNow) # Hours left in the day
m0 <- 60 - minute(timeNow) # Minutes left in the hour
hrsUntilMaturity <- 24 * d0 + h0 + m0 / 60
if(time_step_unit == "min"){
  tStepsUntilMat <- hrsUntilMaturity * 60 / time_step_num
  rTstep_discrete <- (1 + rYrly_discrete)^(1 / (365 * 24 * 60 / time_step_num)) - 1
  rTstep_cont <- log(1 + rTstep_discrete)
}
#------------
#hrsPast...
#------------------------------------------------------------------------
# Parameterize
tau <- tStepsUntilMat
# Get log tStep returns
df$`Log change` <- c(NA, diff(log(df$p)))
lRet <- df$`Log change`[-1]
# Compute s, m
s <- sd(lRet, na.rm = T) / sqrt(tau)
m <- mean(lRet, na.rm = T) / tau + s^2 / 2
cv <- s / (m * sqrt(tau))
r <- rTstep_cont
XoK <- seq(0.5, 1.5, length.out = 50) # X(0)/K - Moneyness
X0 <- df$p[nrow(df)]
K <- X0 / XoK
# European call option value, delta, prob of expiring in the money
dfOut <- OVfun(X0, K, s, m, r, tau)
OV <- dfOut[, 1]
delta <- dfOut[, 2] #N1
probExpInMon <- dfOut[, 3] #N2
# Intrinsic value over moneyness, apart from time value
dfOut <- OVdt0(X0, K, s, m, r, tau)
IntrinOV <- dfOut[, 1]
mnyStar <- dfOut[, 2] # moneyness maximizing IntrinOV
Kstar <- dfOut[, 3]
# Forward contract price
FV <- exp(m * tau) * X0 - exp(-r * tau) * K
# # Derivative envelope (at which the action is stationary; extremal (max or min))
# dfOut <- OVstar(X0, K, s, m, r, tau)
# OVstar <- dfOut[, 1]
# deltaStar <- dfOut[, 2]
#------------------------------------------------------------------------
# Graph
dfPlot <- data.frame(OV, IntrinOV, FV, XoK) %>% gather(Type, Val, OV:FV)
gg <- ggplot(dfPlot, aes(x = XoK, y = Val, group = Type, color = Type))
gg <- gg + geom_line()
gg <- gg + coord_cartesian(xlim = c(0.9, 1.1), ylim = c(-.05, 0.05))
gg <- gg + geom_hline(yintercept = 0, color = "red", linetype = "dashed")
gg <- gg + geom_vline(xintercept = 1, color = "red", linetype = "dashed")
gg <- gg + labs(x = "Moneyness")
gg <- gg + theme_bw()
gg <- gg + theme(legend.position = "top",
                 legend.title = element_blank())
gg_OV <- gg
#--------------------------------------------------------------------
# Histogram of log returns per time step
gg <- ggplot(df, aes(x = `Log change`))
gg <- gg + geom_histogram(color = 4, fill = "white", bins = 20)
#gg <- gg + facet_wrap(~var, ncol = 1, scales = "free")
#gg <- gg + labs(title = "Daily log change")
gg <- gg + theme_bw()
gg <- gg + theme(#axis.title = element_blank(),
                 axis.title.y = element_blank(),
                 #axis.title.x = element_text(size = axisTitleSize),
                 #axis.text = element_text(size = axisTextSize),
                 strip.background = element_rect(fill = "white"),
                 strip.text = element_blank()#,
                 #plot.title = element_text(size = titleSize)
                 )
gg_hist <- gg
#--------------------------------------------------------------------
gg_hist + gg_OV + plot_layout(ncol = 2, widths = c(1 / 2, 1))
#--------------------------------------------------------------------
mnyStar <- round(unique(mnyStar), 5)
Kstar <- round(unique(Kstar), 5)
spot <- round(X0, 5)
mnyCurnt <- round(spot / Kstar, 4)
deltaStar <- round(mnyStar / 2 * exp(-(m + s^2 / 2) * tau), 4)
d2 <- (log(mnyStar) + (m - s^2 / 2) * tau) / (s * sqrt(tau))
probITMstar <- round(pnorm(d2), 4)
d2 <- (log(mnyCurnt) + (m - s^2 / 2) * tau) / (s * sqrt(tau))
probITMcurnt <- round(pnorm(d2), 4)

dfTab <- data.frame(c("Time steps to maturity", "Time step", "Mean log return", "cv log return", "Optimal moneyness", "Optimal Strike", "Spot price", "Current moneyness\nw.r.t optimal strike", "Optimal delta", "Optimal prob ITM", "Current prob ITM\nw.r.t. optimal strike"),
                    c(round(tau, 2), time_step, round(m, 6), round(cv, 4),
                      mnyStar, Kstar, spot, mnyCurnt, deltaStar,
                      probITMstar, probITMcurnt))
colnames(dfTab) <- c("param", "value")
dfTab %>% regulartable() %>% autofit()


```



```{r, echo=FALSE, include=FALSE}
#------------------------------------------------------------
# df_wave <- df[-c(1:(per_ema_for_detrend + 1)), c("date", "date_chr", "p", "ema", "slope")]
df_wave <- df[-c(1:(rollWind + 1)), c("date", "date_chr", "p", "ema", "pctlOsc")]
if(time_step_unit == "min"){
  time_step_num <- as.numeric(stringr::str_extract_all(time_step, "[0-9]+")[[1]])
  slope <- time_step_num / 60
  dj <- 1 / 20
  this_period_label <- "period (minutes)"
}else{
  slope <- 1 #(if daily data)
  dj <- 1 / 250
  this_period_label <- "period (days)"
}

#------------------------------------------------------------
waveAnalysis <- analyze.wavelet(df_wave, "pctlOsc",
# waveAnalysis <- analyze.wavelet(df_wave, "slope",
                                loess.span = 0,
                                slope, #slope = time_step_num / 60 #if time_unit=min
                                dj,
                                lowerPeriod,
                                upperPeriod, 
                                make.pval = TRUE, n.sim = 10,
                                verbose = F)
#------------------------------------------------------------
```

```{r, fig.show = 'hold', fig.align='center', fig.cap="\\label{fig:periods}Extraction of the ts' main cycle period lengths using the WaveletComp package.", fig.width=6, fig.height=3, echo=FALSE}
#------------------------------------------------------------
# Plot beautiful waveComp analysis
# wt.image(waveAnalysis, n.levels = 250, periodlab = "period (active minutes)",legend.params = list(lab = "wavelet power levels"), spec.time.axis = list(at = ind, labels = df_wave$date[ind]))


wtImage <- wt.image(waveAnalysis, n.levels = 250, periodlab = this_period_label, legend.params = list(lab = "wavelet power levels", mar = 4.7))
# my.rec <- reconstruct(my.w)
# x.rec <- my.rec$series$x.r  # x: name of original series
#------------------------------------------------------------
# Get periods and plot periodogram
df_mainCycles <- get_cycles(waveAnalysis)

kable(round(df_mainCycles, 2)) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
#------------------------------------------------------------
```

```{r, echo=FALSE, include=FALSE}
#------------------------------------------------------------
# Get validate (backtest) info
n_backtest = round(backtest_fraction * nrow(df_wave))
ind_fit <- 1:(nrow(df_wave) - n_backtest)
ind_test <- setdiff(1:nrow(df_wave), ind_fit)
#ts <- df_wave$slope[ind_fit]
ts <- df_wave$pctlOsc[ind_fit]
if(time_step_unit == "min"){
  per_vec <- df_mainCycles$Period * 60 / time_step_num
}else{
  per_vec <- df_mainCycles$Period
}
if(!is.null(power_threshold)){
  # Keep only periods above a certain power threshold
  power_threshold_input <- power_threshold
  power_threshold_str <- paste(as.character(stringr::str_extract_all(power_threshold, "[a-z]+")[[1]]), collapse = " ")
  if(power_threshold_str == "drop lowest"){
    power_threshold <- min(df_mainCycles$Power)
  }
  if(power_threshold_str == "percentile log"){
    power_threshold_num <- as.numeric(stringr::str_extract_all(power_threshold, "[0-9.]+")[[1]])
    x <- quantile(log(df_mainCycles$Power), power_threshold_num)
    power_threshold <- exp(x)
  }
  ind_keep <- which(df_mainCycles$Power > power_threshold)
  per_vec <- per_vec[ind_keep]
  
}
out_fitWave <- fitWave(ts, per_vec, pval_thresh = 0.01, n_backtest)
yhat_validate <- out_fitWave[[1]]
ypredict_validate <- out_fitWave[[2]]
#------------------------------------------------------------
# Get predict info
#ts <- df_wave$slope
ts <- df_wave$pctlOsc
n_lookAhead <- round(lookAhead_fraction * length(ts))
out_fitWave <- fitWave(ts, per_vec, pval_thresh = 0.01, n_lookAhead)
yhat_pred <- out_fitWave[[1]]
ypredict_pred <- out_fitWave[[2]]
summod <- out_fitWave[[3]]

```

```{r, echo=FALSE}  

kable(round(xtable(summod), 4)) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```

```{r, fig.show = 'hold', fig.align='center', fig.cap="\\label{fig:valid}Backtest of cyclic model.", fig.height=4, fig.width=7, echo=FALSE}

## Backtest

plot_validation(yhat_validate, ypredict_validate, df_wave)

```


```{r, fig.show = 'hold', fig.cap=c("\\label{fig:pred}Model's prediction.", "\\label{fig:pred_zoom}Zoom in on decisionmaking time window of model's prediction."), fig.align='center', fig.height=4, fig.width=7, echo=FALSE}

## Prediction
n_lookAhead_zoom <- n_lookAhead
n_lookBack_zoom <- round(lookBack_fraction * nrow(df_wave))
plot_prediction(yhat_pred, ypredict_pred, df_wave, time_step, n_lookAhead, n_lookAhead_zoom, n_lookBack_zoom)
#==============================================================
#==============================================================
#==============================================================
# End
#==============================================================
print(symbol_domain)
if(!is.null(stock_symbol)){
  print(stock_symbol)
}else{
  if(is.null(symb_currency_from)){
    print(paste(crypto_symbol_from, "/", crypto_symbol_to))
  }else{
    print(paste(symb_currency_from, "/", symb_currency_to))
  }
}
print(paste("step =", time_step))
print(paste(per_ema_for_detrend, "step detrend"))
print(paste("power_threshold =", power_threshold_input))

```